name: "Deploy website to Cloudflare Pages"
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo ğŸ› ï¸"
        uses: actions/checkout@v4
      - name: "Deploy ğŸš€"
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_DEPLOYMENT_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy . --project-name ${{ github.event.repository.name }}
